data:
  x: INPUT-FILES_SURFACE/xc_once.npy
  y: INPUT-FILES_SURFACE/yc_once.npy
  z: INPUT-FILES_SURFACE/zc_once.npy


configs:
  - Minf: 0.5
    AoA: 0.0
    Pi: 4.0
    variable_names:
      - cfhat
      - cf
      - cphat
      - cp
    long_variable_names:
      - cfhat (globMLP)
      - cf (CFD)
      - cphat (globMLP)
      - cp (CFD)
    filenames:
      - INPUT-FILES_SURFACE/cftesthat_Minf_0.5_AoA_0.0_Pi_4.0.npy
      - INPUT-FILES_SURFACE/cftest_Minf_0.5_AoA_0.0_Pi_4.0.npy
      - INPUT-FILES_SURFACE/cptesthat_Minf_0.5_AoA_0.0_Pi_4.0.npy
      - INPUT-FILES_SURFACE/cptest_Minf_0.5_AoA_0.0_Pi_4.0.npy
    ranges:
      - [0.0, 0.007]
      - [0.0, 0.007]
      - [-1.1, 0.6]
      - [-1.1, 0.6]


  - Minf: 0.82
    AoA: 3.0
    Pi: 2.0
    variable_names:
      - cfhat
      - cf
      - cphat
      - cp
    long_variable_names:
      - cfhat (globMLP)
      - cf (CFD)
      - cphat (globMLP)
      - cp (CFD)
    filenames:
      - INPUT-FILES_SURFACE/cftesthat_Minf_0.82_AoA_3.0_Pi_2.0.npy
      - INPUT-FILES_SURFACE/cftest_Minf_0.82_AoA_3.0_Pi_2.0.npy
      - INPUT-FILES_SURFACE/cptesthat_Minf_0.82_AoA_3.0_Pi_2.0.npy
      - INPUT-FILES_SURFACE/cptest_Minf_0.82_AoA_3.0_Pi_2.0.npy
    ranges:
      - [0.0, 0.007]
      - [0.0, 0.007]
      - [-1.1, 0.6]
      - [-1.1, 0.6]


  - Minf: 0.85
    AoA: 1.5
    Pi: 1.0
    variable_names:
      - cfhat
      - cf
      - cphat
      - cp
    long_variable_names:
      - cfhat (globMLP)
      - cf (CFD)
      - cphat (globMLP)
      - cp (CFD)
    filenames:
      - INPUT-FILES_SURFACE/cftesthat_Minf_0.85_AoA_1.5_Pi_1.0.npy
      - INPUT-FILES_SURFACE/cftest_Minf_0.85_AoA_1.5_Pi_1.0.npy
      - INPUT-FILES_SURFACE/cptesthat_Minf_0.85_AoA_1.5_Pi_1.0.npy
      - INPUT-FILES_SURFACE/cptest_Minf_0.85_AoA_1.5_Pi_1.0.npy
    ranges:
      - [0.0, 0.007]
      - [0.0, 0.007]
      - [-1.1, 0.6]
      - [-1.1, 0.6]


  - Minf: 0.96
    AoA: -2.0
    Pi: 2.0
    variable_names:
      - cfhat
      - cf
      - cphat
      - cp
    long_variable_names:
      - cfhat (globMLP)
      - cf (CFD)
      - cphat (globMLP)
      - cp (CFD)
    filenames:
      - INPUT-FILES_SURFACE/cftesthat_Minf_0.96_AoA_-2.0_Pi_2.0.npy
      - INPUT-FILES_SURFACE/cftest_Minf_0.96_AoA_-2.0_Pi_2.0.npy
      - INPUT-FILES_SURFACE/cptesthat_Minf_0.96_AoA_-2.0_Pi_2.0.npy
      - INPUT-FILES_SURFACE/cptest_Minf_0.96_AoA_-2.0_Pi_2.0.npy
    ranges:
      - [0.0, 0.007]
      - [0.0, 0.007]
      - [-1.1, 0.6]
      - [-1.1, 0.6]


camera_settings:
  elevation: 50.0
  azimuth: 120.0
  zoom: 1.0
  xlim: [null, null]
  ylim: [null, 5.0]
  zlim: [null, null]
  xoffsets: [10.0, -14.0]
  yoffsets: [0.0, 0.0]
  zoffsets: [0.0, 0.0]


plot_settings:
  figsize: [8.5, 4.8]
  dpi: 400
  output_folder: PLOTS_SCATTER-AND-SLICES
  filename: figscatter
  title: WT
  title_fontsize: 12
  cmap: jet
  cbar:
    title: null
    title_fontsize: 8
    ticks_fontsize: 6
  right_panel:
    show: true
    figure_rootnames:
      - PLOTS_SLICES/fig_slicey13.4
      - PLOTS_SLICES/fig_slicey21.9
      - PLOTS_SLICES/fig_slicey26.0

miscellaneous:
  verbose: true
